name: Continuous Integration

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run eslint
        run: npm run lint

      - name: Test TODO
        run: echo "Running tests"

      # - name: Build Android Debug APK
      #   run: npx react-native run-android --variant=debug

      # - name: Upload APK
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: app-debug.apk
      #     path: android/app/build/outputs/apk/debug/app-debug.apk

